### ISSUE TITLE
SWRST Operation

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter-testing#5]
The SWRST line is driven by GPIO 17, but this GPIO fails when exercised with the test script.
Attempting to drive this GPIO from the test program fails as it is not exported to create the directory in /sys/class/gpio
It does not appear to have any special function.
It may be reserved by current firmware.

**Comment by tgillett** [comment]
GPIO 17 has been tested to work ok with new firmware.

This issue can be closed.
