### ISSUE TITLE
GPIO Operation

### ISSUE THREAD

**Issue by nicopace** [libremesh/librerouter-testing#6]
GPIOs 0, 1, 2, 3, 4, 13 fail testing as simple GPIOs.
These GPIOs have reserved functions and will require system configuration to test operation.

GPIOs 17, 23 fail testing as simple GPIOs.
These GPIOs do not appear to have reserved functions.

It is possible that they have been used by kernel code in the firmwware which was copied from a different board. This will be resolved when firmware is built for the board.

GPIO17 is used for SWRST line (from Reset Button SW1 and I/O connectors)
GPIO23 is used for STATUS LED

See QCA9558 Datasheet

* pp70 Table 3-16 Default GPIO Signals
* pp47 Bootstrap Options

**Comment by tgillett** [comment]
With new test firmware, the following GPIOs now pass testing:
GPIO   0 - J13, pin 2
GPIO   1 - J13, pin 4
GPIO   2 - J13, pin 6
GPIO   3 - J13, pin 10
GPIO   4 - J13, pin 7
GPIO 13 - J1, pin  10
GPIO 17 -  J1, pin 11
GPIO 23 - Status LED

This issue can now be closed.
